// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3JlqyrrST7wTCjluvtxlL0D5ZQQiyPE',
    appId: '1:28066521495:web:36a56d7984239c167b64d2',
    messagingSenderId: '28066521495',
    projectId: 'wwjd-di-e36ce',
    authDomain: 'wwjd-di-e36ce.firebaseapp.com',
    storageBucket: 'wwjd-di-e36ce.firebasestorage.app',
    measurementId: 'G-X3NPYY834K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7a8J7ViDCeBZUjsm6YnZLVu6KeAMSHQI',
    appId: '1:28066521495:android:2897b9f668922af97b64d2',
    messagingSenderId: '28066521495',
    projectId: 'wwjd-di-e36ce',
    storageBucket: 'wwjd-di-e36ce.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwYqodPlNVbZ385RW5Oro6oCe6EWCFWU',
    appId: '1:28066521495:ios:9cfb6eb513c0fd1b7b64d2',
    messagingSenderId: '28066521495',
    projectId: 'wwjd-di-e36ce',
    storageBucket: 'wwjd-di-e36ce.firebasestorage.app',
    iosBundleId: 'com.example.wwjdApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwYqodPlNVbZ385RW5Oro6oCe6EWCFWU',
    appId: '1:28066521495:ios:9cfb6eb513c0fd1b7b64d2',
    messagingSenderId: '28066521495',
    projectId: 'wwjd-di-e36ce',
    storageBucket: 'wwjd-di-e36ce.firebasestorage.app',
    iosBundleId: 'com.example.wwjdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd3JlqyrrST7wTCjluvtxlL0D5ZQQiyPE',
    appId: '1:28066521495:web:36a56d7984239c167b64d2',
    messagingSenderId: '28066521495',
    projectId: 'wwjd-di-e36ce',
    authDomain: 'wwjd-di-e36ce.firebaseapp.com',
    storageBucket: 'wwjd-di-e36ce.firebasestorage.app',
    measurementId: 'G-X3NPYY834K',
  );
}
