#!/usr/bin/env python3
"""Generate CCC paragraph -> Vatican content URL breakpoints from scborromeo.org."""
import re
import urllib.request

OUTPUT = "lib/core/ccc_breakpoints.dart"

WORDS = {
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
}


def num_word(n: int) -> str:
    return WORDS.get(n, str(n))


def legacy_to_vatican(legacy: str) -> str | None:
    m = re.match(r"p(\d+)s(\d+)c(\d+)a(\d+)\.htm", legacy, re.I)
    if not m:
        return None
    p, s, c, a = (int(x) for x in m.groups())
    if p < 1 or p > 4:
        return None
    part = ["one", "two", "three", "four"][p - 1]
    return (
        f"part_{part}/section_{num_word(s)}/chapter_{num_word(c)}/article_{a}.html"
    )


def main() -> None:
    breakpoints: list[tuple[int, str]] = []
    legacy_files: list[str] = []

    for p in range(1, 5):
        for s in range(1, 4):
            for c in range(1, 8):
                for a in range(1, 9):
                    legacy_files.append(f"p{p}s{s}c{c}a{a}.htm")

    for link in legacy_files:
        url = f"https://www.scborromeo.org/ccc/{link}"
        try:
            page = urllib.request.urlopen(url, timeout=10).read().decode(
                "latin-1", errors="ignore"
            )
        except OSError:
            continue
        if "404" in page[:200].lower():
            continue
        m = re.search(r"<A NAME=(\d+)>", page, re.I)
        if not m:
            continue
        start = int(m.group(1))
        vpath = legacy_to_vatican(link)
        if vpath:
            breakpoints.append((start, vpath, link))

    breakpoints.sort(key=lambda x: x[0])
    # Deduplicate vatican paths keeping earliest paragraph
    seen_paths: set[str] = set()
    unique: list[tuple[int, str, str]] = []
    for start, path, legacy in breakpoints:
        if path in seen_paths:
            continue
        seen_paths.add(path)
        unique.append((start, path, legacy))

    lines = [
        "// GENERATED by scripts/generate_ccc_breakpoints.py — do not edit by hand.",
        "const cccVaticanBreakpoints = <({int start, String vaticanPath, String legacyFile})>[",
    ]
    for start, path, legacy in unique:
        lines.append(f"  (start: {start}, vaticanPath: '{path}', legacyFile: '{legacy}'),")
    lines.append("];")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {len(unique)} breakpoints to {OUTPUT}")


if __name__ == "__main__":
    main()
